# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/e/proyectos/KOs-System

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/e/proyectos/KOs-System

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/proyectos/KOs-System/CMakeFiles /mnt/e/proyectos/KOs-System//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/proyectos/KOs-System/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kernel_objs

# Build rule for target.
kernel_objs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kernel_objs
.PHONY : kernel_objs

# fast build rule for target.
kernel_objs/fast:
	$(MAKE) $(MAKESILENT) -f kernel/cmake/CMakeFiles/kernel_objs.dir/build.make kernel/cmake/CMakeFiles/kernel_objs.dir/build
.PHONY : kernel_objs/fast

#=============================================================================
# Target rules for targets named kernel_bin

# Build rule for target.
kernel_bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kernel_bin
.PHONY : kernel_bin

# fast build rule for target.
kernel_bin/fast:
	$(MAKE) $(MAKESILENT) -f kernel/cmake/CMakeFiles/kernel_bin.dir/build.make kernel/cmake/CMakeFiles/kernel_bin.dir/build
.PHONY : kernel_bin/fast

#=============================================================================
# Target rules for targets named app_support_objs

# Build rule for target.
app_support_objs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app_support_objs
.PHONY : app_support_objs

# fast build rule for target.
app_support_objs/fast:
	$(MAKE) $(MAKESILENT) -f kernel/cmake/CMakeFiles/app_support_objs.dir/build.make kernel/cmake/CMakeFiles/app_support_objs.dir/build
.PHONY : app_support_objs/fast

#=============================================================================
# Target rules for targets named hello_obj

# Build rule for target.
hello_obj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hello_obj
.PHONY : hello_obj

# fast build rule for target.
hello_obj/fast:
	$(MAKE) $(MAKESILENT) -f kernel/cmake/CMakeFiles/hello_obj.dir/build.make kernel/cmake/CMakeFiles/hello_obj.dir/build
.PHONY : hello_obj/fast

#=============================================================================
# Target rules for targets named hello.elf

# Build rule for target.
hello.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hello.elf
.PHONY : hello.elf

# fast build rule for target.
hello.elf/fast:
	$(MAKE) $(MAKESILENT) -f kernel/cmake/CMakeFiles/hello.elf.dir/build.make kernel/cmake/CMakeFiles/hello.elf.dir/build
.PHONY : hello.elf/fast

#=============================================================================
# Target rules for targets named echo_obj

# Build rule for target.
echo_obj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 echo_obj
.PHONY : echo_obj

# fast build rule for target.
echo_obj/fast:
	$(MAKE) $(MAKESILENT) -f kernel/cmake/CMakeFiles/echo_obj.dir/build.make kernel/cmake/CMakeFiles/echo_obj.dir/build
.PHONY : echo_obj/fast

#=============================================================================
# Target rules for targets named echo.elf

# Build rule for target.
echo.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 echo.elf
.PHONY : echo.elf

# fast build rule for target.
echo.elf/fast:
	$(MAKE) $(MAKESILENT) -f kernel/cmake/CMakeFiles/echo.elf.dir/build.make kernel/cmake/CMakeFiles/echo.elf.dir/build
.PHONY : echo.elf/fast

#=============================================================================
# Target rules for targets named ls_obj

# Build rule for target.
ls_obj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ls_obj
.PHONY : ls_obj

# fast build rule for target.
ls_obj/fast:
	$(MAKE) $(MAKESILENT) -f kernel/cmake/CMakeFiles/ls_obj.dir/build.make kernel/cmake/CMakeFiles/ls_obj.dir/build
.PHONY : ls_obj/fast

#=============================================================================
# Target rules for targets named ls.elf

# Build rule for target.
ls.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ls.elf
.PHONY : ls.elf

# fast build rule for target.
ls.elf/fast:
	$(MAKE) $(MAKESILENT) -f kernel/cmake/CMakeFiles/ls.elf.dir/build.make kernel/cmake/CMakeFiles/ls.elf.dir/build
.PHONY : ls.elf/fast

#=============================================================================
# Target rules for targets named apps

# Build rule for target.
apps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 apps
.PHONY : apps

# fast build rule for target.
apps/fast:
	$(MAKE) $(MAKESILENT) -f kernel/cmake/CMakeFiles/apps.dir/build.make kernel/cmake/CMakeFiles/apps.dir/build
.PHONY : apps/fast

#=============================================================================
# Target rules for targets named iso

# Build rule for target.
iso: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 iso
.PHONY : iso

# fast build rule for target.
iso/fast:
	$(MAKE) $(MAKESILENT) -f kernel/cmake/CMakeFiles/iso.dir/build.make kernel/cmake/CMakeFiles/iso.dir/build
.PHONY : iso/fast

#=============================================================================
# Target rules for targets named qemu

# Build rule for target.
qemu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qemu
.PHONY : qemu

# fast build rule for target.
qemu/fast:
	$(MAKE) $(MAKESILENT) -f kernel/cmake/CMakeFiles/qemu.dir/build.make kernel/cmake/CMakeFiles/qemu.dir/build
.PHONY : qemu/fast

#=============================================================================
# Target rules for targets named qemu-vvfat

# Build rule for target.
qemu-vvfat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qemu-vvfat
.PHONY : qemu-vvfat

# fast build rule for target.
qemu-vvfat/fast:
	$(MAKE) $(MAKESILENT) -f kernel/cmake/CMakeFiles/qemu-vvfat.dir/build.make kernel/cmake/CMakeFiles/qemu-vvfat.dir/build
.PHONY : qemu-vvfat/fast

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) $(MAKESILENT) -f kernel/cmake/CMakeFiles/debug.dir/build.make kernel/cmake/CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named gdb

# Build rule for target.
gdb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gdb
.PHONY : gdb

# fast build rule for target.
gdb/fast:
	$(MAKE) $(MAKESILENT) -f kernel/cmake/CMakeFiles/gdb.dir/build.make kernel/cmake/CMakeFiles/gdb.dir/build
.PHONY : gdb/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... apps"
	@echo "... debug"
	@echo "... echo.elf"
	@echo "... gdb"
	@echo "... hello.elf"
	@echo "... iso"
	@echo "... kernel_bin"
	@echo "... ls.elf"
	@echo "... qemu"
	@echo "... qemu-vvfat"
	@echo "... app_support_objs"
	@echo "... echo_obj"
	@echo "... hello_obj"
	@echo "... kernel_objs"
	@echo "... ls_obj"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

